app.py
import os
from flask import Flask 
from routes import pages
from pymongo import MongoClient
from dotenv import load_dotenv

load_dotenv()


def create_app():
    app = Flask(__name__)
    app.register_blueprint(pages)
    client = MongoClient(os.environ.get("MONGODB_URI"))
    app.db = client.get_default_database()
    
    return app 


routes.py
import datetime
import uuid
from flask import Blueprint, current_app, render_template, request, redirect, url_for

pages = Blueprint("habits", __name__, template_folder="templates", static_folder="static")

@pages.context_processor
def add_calc_date_range():
    def date_range(start: datetime.datetime):
        dates = [start + datetime.timedelta(days=diff) for diff in range(-3, 4)]
        return dates
    return {"date_range": date_range}

def today_at_midnight():
    today = datetime.datetime.today()
    return datetime.datetime(today.year, today.month, today.day)

@pages.route("/")
def index():
    date_str = request.args.get("date")
    if date_str: 
        selected_date = datetime.datetime.fromisoformat(date_str)
    else: 
        selected_date = today_at_midnight()
    
    habits_on_date = current_app.db.habits.find({"added": {"$lte": selected_date}})
    
    completions = [
        habit["habit"]
        for habit in current_app.db.completions.find({"date": selected_date})
    ]
    
    
    return render_template (
        "index.html",
        habits=habits_on_date,
        completions=completions,
        selected_date=selected_date, 
        title="Billy's Diary - Home",
    )

@pages.route("/add", methods=["GET", "POST"])
def add_habit():
    today = today_at_midnight()
    
    if request.form:
        current_app.db.habits.insert_one(
            {"_id": uuid.uuid4().hex, "added": today, "name": request.form.get("habit")}
        )
        
    return render_template(
        "add_habit.html", 
        title="Billy's Diray - Add Billyday", 
        selected_date=today,
    )

@pages.route("/complete", methods=["POST"])
def complete():
    date_string = request.form.get("date")
    habit = request.form.get("habitId")
    date = datetime.datetime.fromisoformat(date_string)
    current_app.db.completions.insert_one({"date": date, "habit": habit})
    return redirect(url_for(".index", date=date_string))

templates/add_habit.html
{% extends "layout.html" %}
{% block main_content %}
    <form class="form" method="POST">
        <textarea class="form__input" id="habit" name="habit" rows="3" placeholder="Add a new Billyday"></textarea>
        <button type="submit" class="form__button">Bilyday</button>
    </form>
{% endblock %}

templates/index.html
{% extends "layout.html" %}
{% block main_content %}

    <section class="habit-list">
    {% for habit in habits %}
        {% set completed = habit["_id"] in completions %}
        {% if completed %}
        <div class="habit__completed">
            <p class="habit__name">{{ habit["name"] }}</p>
            <svg class="habit__icon" width="72" height="65" viewBox="0 0 72 65" fill="none" xmlns="http://www.w3.org/2000/svg">
                <circle cx="9.23862" cy="37.6155" r="8" transform="rotate(9.74404 9.23862 37.6155)" fill="#E9A883"/>
                <path d="M12.4266 30.0459L45.4259 50.0564L37.1298 63.7375L4.1305 43.7271L12.4266 30.0459Z" fill="#E9A883"/>
                <path d="M24 55.7483L58.0202 -3.8389e-05L71.678 8.33456L37.6578 64.0829L24 55.7483Z" fill="#E9A883"/>
                <line x1="0.223607" y1="35.5528" x2="6.22361" y2="38.5528" stroke="#D76F35"/>
                <line x1="4.22361" y1="30.5528" x2="10.2236" y2="33.5528" stroke="#D76F35"/>
                <line x1="1.22361" y1="32.5528" x2="7.22361" y2="35.5528" stroke="#D76F35"/>
                <line x1="47.265" y1="29.576" x2="55.265" y2="34.576" stroke="#EECFBE"/>
                <line x1="50.2394" y1="12.5611" x2="61.2394" y2="18.5611" stroke="#EECFBE"/>
                <line x1="35.2394" y1="44.5611" x2="46.2394" y2="50.5611" stroke="#EECFBE"/>
            </svg> 
        </div> 
        {% else %}
            <div class="habit">
                <form method="POST" class="habit__form" action="{{ url_for('habits.complete')}}" >
                    <input type="hidden" name="habitId" value="{{ habit['_id'] }}" />
                    <input type="hidden" name="date" value="{{ selected_date}}" />
                    <button type="submit" class="habit__button">
                        {{ habit["name"] }}
                    </button>
                </form>
            </div>
        {% endif%}    
    {% endfor %}
    </section>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>{{ title }}</title>
        <link href="https://fonts.googleapis.com/css2?family=Amatic+SC&family=Roboto:wght@100&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css')}}">

        {% block head_content %} {% endblock %}
    </head>

    <body>
        <header class="header">
            <h1 class="header__logo"><a href="{{ url_for('habits.index')}}" class="header__link">Billy's Diary</a></h1>
            {% if "add" not in request.endpoint %}
                <a href="{{ url_for('habits.add_habit')}}" class="header__link">+ Add Story</a>
            {% endif%}
            </header>

        <main class="main">
            <section class="dates">
                {% for date in date_range(selected_date) %}
                    <a
                        class="dates__link {{ 'dates__link--current' if loop.index0 == 3 else '' }}"
                        href="{{ url_for('habits.index', date=date) }}"
                    >
                    <time class="date" datetime="{{ date}}">
                        <span> {{ date.strftime("%a") }} </span>
                        <span> {{ date.strftime("%d") }} </span>
                    </time>
                    </a>
                {% endfor %}
            </section>
            {% block main_content %}
            {% endblock %}
        </main>
    </body>
</html>